services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    network_mode: host # Mandatory for mDNS/IPv6 Discovery
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/ethan/docker/matter_config:/data
      - /run/dbus:/run/dbus:ro # Required for BLE Handshaking
