version: "3.8"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8888:8080" # Using 8888 to avoid conflict with qbittorrent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
