version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      - UID=1000
      - GID=1000
      - EULA=TRUE
      - TYPE=PAPER            # Recommended for performance
      - VERSION=LATEST
      - MEMORY=4G
      
      # World Generation
      - SEED=69420018030897796    # The specific seed you requested
      - LEVEL_TYPE=DEFAULT        # Ensures standard "Normal" terrain generation
      
      # Admin Configuration
      - OPS=ethan_h2003
      
      # RCON Configuration
      - ENABLE_RCON=true
      - RCON_PASSWORD=minecraft
      
      # Startup Commands
      - RCON_CMDS_STARTUP=gamerule keepInventory true
      
    volumes:
      - /home/ethan/docker/minecraft_new_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
