services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    shm_size: "512mb"
    cpus: "2.0"
    mem_limit: "3g"
    mem_reservation: "1536m"
    memswap_limit: "3g"
    pids_limit: 768
    cap_add:
      - PERFMON
    group_add:
      - "993" # render
      - "44"  # video
      - "46"  # plugdev
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "127.0.0.1:5000:5000"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/data_14tb/media/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
