services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
    - 80:80
    - 81:81
    - 443:443
    volumes:
    - ./nginx_config/data:/data
    - ./nginx_config/letsencrypt:/etc/letsencrypt
    networks:
    - proxy_net
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:80 || wget -q --spider http://localhost:80 || exit
        1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  proxy_net:
    external: true
